

-- short

SHORT_STOP_ACTIVE = {
    ['condition_price2']        = 0.0;
    ['seccode']                 = 'SRH2';
    ['firmid']                  = 'SPBFUT';
    ['trans_id']                = 1000325;
    ['account']                 = 'SPBFUTJRk1N';
    ['class_code']              = 'SPBFUT';
    ['expiry']                  = 20220124;
    ['sec_code']                = 'SRH2';
    ['condition_class_code']    = 'SPBFUT';
    ['linkedorder']             = 0;
    ['condition_sec_code']      = 'SRH2';
    ['withdraw_time']           = 0;
    ['co_order_num']            = 0;
    ['ordernum']                = 1675296;
    ['price']                   = 26886.0;
    ['client_code']             = 'SPBFUTJRk1N';
    ['uid']                     = 77133;
    ['offset']                  = 0.0;
    ['brokerref']               = 'short open';
    ['orderdate']               = 20220124;
    ['flags']                   = 29;
    ['spread']                  = 0.0;
    ['condition']               = 4;
    ['alltrade_num']            = 0;
    ['condition_price']         = 26965.0;
    ['balance']                 = 4.0;
    ['ordertime']               = 211537;
    ['stop_order_type']         = 1;
    ['condition_seccode']       = 'SRH2';
    ['active_from_time']        = 0;
    ['qty']                     = 4.0;
    ['filled_qty']              = 0.0;
    ['active_to_time']          = 0;
    ['stopflags']               = 32;
    ['order_num']               = 1675296;
    ['canceled_uid']            = 0;
    ['co_order_price']          = 0.0;

}


SHORT_STOP_ACTIVATED_1 = {
    ['order_num']                   = 1675175;
    ['filled_qty']                  = 5.0;
    ['trans_id']                    = 1000311;
    ['client_code']                 = 'SPBFUTJRk1N';
    ['stopflags']                   = 32;
    ['ordertime']                   = 210009;
    ['offset']                      = 0.0;
    ['price']                       = 27057.0;
    ['withdraw_time']               = 0;
    ['brokerref']                   = 'long open';
    ['flags']                       = 24;
    ['linkedorder']                 = 0;
    ['account']                     = 'SPBFUTJRk1N';
    ['condition_seccode']           = 'SRH2';
    ['condition']                   = 5;
    ['active_to_time']              = 0;
    ['alltrade_num']                = 1953472373147572331;
    ['stop_order_type']             = 1;
    ['firmid']                      = 'SPBFUT';
    ['spread']                      = 0.0;
    ['condition_price2']            = 0.0;
    ['seccode']                     = 'SRH2';
    ['co_order_num']                = 0;
    ['uid']                         = 77133;
    ['class_code']                  = 'SPBFUT';
    ['condition_sec_code']          = 'SRH2';
    ['orderdate']                   = 20220124;
    ['canceled_uid']                = 0;
    ['active_from_time']            = 0;
    ['ordernum']                    = 1675175;
    ['condition_class_code']        = 'SPBFUT';
    ['balance']                     = 0.0;
    ['condition_price']             = 26978.0;
    ['sec_code']                    = 'SRH2';
    ['co_order_price']              = 0.0;
    ['expiry']                      = 20220124;
    ['qty']                         = 5.0;
}
SHORT_STOP_ACTIVATED_2 = {
    ['order_num']                   = 1675175;
    ['filled_qty']                  = 5.0;
    ['trans_id']                    = 1000311;
    ['client_code']                 = 'SPBFUTJRk1N';
    ['stopflags']                   = 32;
    ['ordertime']                   = 210009;
    ['offset']                      = 0.0;
    ['price']                       = 27057.0;
    ['withdraw_time']               = 0;
    ['brokerref']                   = 'long open';
    ['flags']                       = 24;
    ['linkedorder']                 = 1953472373147613705;
    ['account']                     = 'SPBFUTJRk1N';
    ['condition_seccode']           = 'SRH2';
    ['condition']                   = 5;
    ['active_to_time']              = 0;
    ['alltrade_num']                = 1953472373147572331;
    ['stop_order_type']             = 1;
    ['firmid']                      = 'SPBFUT';
    ['spread']                      = 0.0;
    ['condition_price2']            = 0.0;
    ['seccode']                     = 'SRH2';
    ['co_order_num']                = 0;
    ['uid']                         = 77133;
    ['class_code']                  = 'SPBFUT';
    ['condition_sec_code']          = 'SRH2';
    ['orderdate']                   = 20220124;
    ['canceled_uid']                = 0;
    ['active_from_time']            = 0;
    ['ordernum']                    = 1675175;
    ['condition_class_code']        = 'SPBFUT';
    ['balance']                     = 0.0;
    ['condition_price']             = 26978.0;
    ['sec_code']                    = 'SRH2';
    ['co_order_price']              = 0.0;
    ['expiry']                      = 20220124;
    ['qty']                         = 5.0;
}


SHORT_ORDER_1 = {
    ['order_num']                           = 1953472373147613705;
    ['repoterm']                            = 0;
    ['trans_id']                            = 0;
    -- ['exchange_code']= ;
    -- ['userid']= ;
    ['capacity']                            = 0;
    ['client_code']                         = 'SPBFUTJRk1N';
    ['passive_only_order']                  = 0;
    ['uid']                                 = 0;
    ['executing_trader_short_code']         = 0;
    ['price']                               = 27057.0;
    ['executing_trader_qualifier']          = 0;
    ['brokerref']                           = 'long open';
    ['flags']                               = 24;
    ['balance']                             = 0.0;
    ['investment_decision_maker_qualifier'] = 0;
    -- ['bank_acc_id']= ;
    -- ['extref']= ;
    ['account']                             = 'SPBFUTJRk1N';
    ['start_discount']                      = 0;
    -- ['settlecode']= ;
    ['value']                               = 135285.0;
    ['client_short_code']                   = 0;
    ['client_qualifier']                    = 0;
    ['on_behalf_of_uid']                    = 0;
    -- ['settle_currency']= ;
    ['awg_price']                           = 0.0;
    ['linkedorder']                         = 0;
    ['firmid']                              = 'SPBFUT';
    ['exec_type']                           = 0;
    ['filled_value']                        = 0.0;
    -- ['price_currency']= ;
    ['revision_number']                     = 0;
    ['seccode']                             = 'SRH2';
    ['ext_order_status']                    = 0;
    ['canceled_uid']                        = 0;
    ['visible']                             = 0.0;
    ['investment_decision_maker_short_code']= 0;
    ['activation_time']                     = 0;
    ['accruedint']                          = 0.0;
    ['expiry_time']                         = -1;
    ['side_qualifier']                      = 0;
    ['repovalue']                           = 0.0;
    ['acnt_type']                           = 0;
    ['ext_order_flags']                     = 0;
    ['min_qty']                             = 0.0;
    -- ['reject_reason']= ;
    ['repo_value_balance']                  = 0.0;
    ['repo2value']                          = 0.0;
    ['qty']                                 = 5.0;
    ['ordernum']                            = 1953472373147613705;
    ['expiry']                              = -1;
    ['price2']                              = 0.0;
    ['class_code']                          = 'SPBFUT';
    ['sec_code']                            = 'SRH2';
    ['accepted_uid']                        = 0;
    ['value_entry_type']                    = 0;
    ['yield']                               = 0.0;
}
SHORT_ORDER_2 = {
    ['order_num']                           = 1953472373147613705;
    ['repoterm']                            = 0;
    ['trans_id']                            = 0;
    -- exchange_code: ;
    -- userid: ;
    ['capacity']                            = 0;
    ['client_code']                         = 'SPBFUTJRk1N';
    ['passive_only_order']                  = 0;
    ['uid']                                 = 0;
    ['executing_trader_short_code']         = 0;
    ['price']                               = 27057.0;
    ['executing_trader_qualifier']          = 0;
    ['brokerref']                           = 'long open';
    ['flags']                               = 1048600;
    ['balance']                             = 0.0;
    ['investment_decision_maker_qualifier'] = 0;
    -- bank_acc_id: ;
    -- extref: ;
    ['account']                             = 'SPBFUTJRk1N';
    ['start_discount']                      = 0;
    -- settlecode: ;
    ['value']                               = 135285.0;
    ['client_short_code']                   = 0;
    ['client_qualifier']                    = 0;
    ['on_behalf_of_uid']                    = 0;
    -- settle_currency: ;
    ['awg_price']                           = 0.0;
    ['linkedorder']                         = 1675175;
    ['firmid']                              = 'SPBFUT';
    ['exec_type']                           = 0;
    ['filled_value']                        = 0.0;
    -- price_currency: ;
    ['revision_number']                     = 0;
    ['seccode']                             = 'SRH2';
    ['ext_order_status']                    = 0;
    ['canceled_uid']                        = 0;
    ['visible']                             = 0.0;
    ['investment_decision_maker_short_code']= 0;
    ['activation_time']                     = 0;
    ['accruedint']                          = 0.0;
    ['expiry_time']                         = -1;
    ['side_qualifier']                      = 0;
    ['repovalue']                           = 0.0;
    ['acnt_type']                           = 0;
    ['ext_order_flags']                     = 0;
    ['min_qty']                             = 0.0;
    -- reject_reason: ;
    ['repo_value_balance']                  = 0.0;
    ['repo2value']                          = 0.0;
    ['qty']                                 = 5.0;
    ['ordernum']                            = 1953472373147613705;
    ['expiry']                              = -1;
    ['price2']                              = 0.0;
    ['class_code']                          = 'SPBFUT';
    ['sec_code']                            = 'SRH2';
    ['accepted_uid']                        = 0;
    ['value_entry_type']                    = 0;
    ['yield']                               = 0.0;
}
SHORT_ORDER_3 = {
    ['order_num']                           = 1953472373147613705;
    ['repoterm']                            = 0;
    ['trans_id']                            = 1000311;
    -- exchange_code: ;
    -- userid: ;
    ['capacity']                            = 0;
    ['client_code']                         = 'SPBFUTJRk1N';
    ['passive_only_order']                  = 0;
    ['uid']                                 = 77133;
    ['executing_trader_short_code']         = 0;
    ['price']                               = 27057.0;
    ['executing_trader_qualifier']          = 0;
    ['brokerref']                           = 'long open';
    ['flags']                               = 1048600;
    ['balance']                             = 0.0;
    ['investment_decision_maker_qualifier'] = 0;
    -- bank_acc_id: ;
    -- extref: ;
    ['account']                             = 'SPBFUTJRk1N';
    ['start_discount']                      = 0;
    -- settlecode: ;
    ['value']                               = 135285.0;
    ['client_short_code']                   = 0;
    ['client_qualifier']                    = 0;
    ['on_behalf_of_uid']                    = 0;
    -- settle_currency: ;
    ['awg_price']                           = 0.0;
    ['linkedorder']                         = 1675175;
    ['firmid']                              = 'SPBFUT';
    ['exec_type']                           = 0;
    ['filled_value']                        = 0.0;
    -- price_currency: ;
    ['revision_number']                     = 0;
    ['seccode']                             = 'SRH2';
    ['ext_order_status']                    = 0;
    ['canceled_uid']                        = 0;
    ['visible']                             = 0.0;
    ['investment_decision_maker_short_code']= 0;
    ['activation_time']                     = 0;
    ['accruedint']                          = 0.0;
    ['expiry_time']                         = -1;
    ['side_qualifier']                      = 0;
    ['repovalue']                           = 0.0;
    ['acnt_type']                           = 0;
    ['ext_order_flags']                     = 0;
    ['min_qty']                             = 0.0;
    -- reject_reason: ;
    ['repo_value_balance']                  = 0.0;
    ['repo2value']                          = 0.0;
    ['qty']                                 = 5.0;
    ['ordernum']                            = 1953472373147613705;
    ['expiry']                              = -1;
    ['price2']                              = 0.0;
    ['class_code']                          = 'SPBFUT';
    ['sec_code']                            = 'SRH2';
    ['accepted_uid']                        = 0;
    ['value_entry_type']                    = 0;
    ['yield']                               = 0.0;
}


SHORT_TRADE_1_1 = {
    ['tradenum']= 1953472373147572640;
    ['firmid']= 'SPBFUT';
    ['side_qualifier']= 0;
    ['account']= 'SPBFUTJRk1N';
    ['lower_discount']= 0.0;
    -- station_id: ;
    ['client_qualifier']= 0;
    ['otc_post_trade_indicator']= 0;
    ['block_securities']= 0;
    -- order_exchange_code: ;
    -- clearing_firmid: ;
    ['kind']= 1;
    ['liquidity_indicator']= 0;
    ['accruedint']= 0.0;
    ['settle_currency']= 'SUR';
    ['settlecode']= 'T1';
    ['exchange_comission']= 5.34;
    ['uid']= 77133;
    -- userid: ;
    ['settle_date']= 20220125;
    ['brokerref']= 'short open';
    ['trade_num']= 1953472373147572640;
    ['order_qty']= 0.0;
    -- lseccode: ;
    ['ext_trade_flags']= 0;
    -- extref: ;
    ['price2']= 0.0;
    ['qty']= 3.0;
    ['yield']= 0.0;
    ['canceled_uid']= 0;
    -- cpfirmid: ;
    ['reporate']= 0.0;
    ['seccode']= 'SRH2';
    ['trans_id']= 1000325;
    ['accrued2']= 0.0;
    ['class_code']= 'SPBFUT';
    ['tech_center_comission']= 0.0;
    -- system_ref: ;
    ['on_behalf_of_uid']= 0;
    ['investment_decision_maker_qualifier']= 0;
    ['repo2value']= 0.0;
    -- bank_acc_id: ;
    ['order_revision_number']= 0;
    ['order_price']= 0.0;
    ['clearing_comission']= 0.0;
    ['executing_trader_qualifier']= 0;
    ['client_code']= 'SPBFUTJRk1N';
    -- clearing_bank_accid: ;
    -- exchange_code: ;
    ['cross_rate']= 0.0;
    ['capacity']= 0;
    ['mleg_base_sid']= -1;
    ['trade_currency']= 'SUR';
    ['waiver_flag']= 0;
    ['client_short_code']= 0;
    ['broker_comission']= 0.0;
    ['value']= 80838.0;
    -- exec_market: ;
    ['repovalue']= 0.0;
    ['executing_trader_short_code']= 0;
    ['ordernum']= 1953472373147616650;
    ['period']= 1;
    ['upper_discount']= 0.0;
    ['sec_code']= 'SRH2';
    ['linked_trade']= 0;
    ['start_discount']= 0.0;
    ['investment_decision_maker_short_code']= 0;
    ['repoterm']= 0;
    ['order_num']= 1953472373147616650;
    ['price']= 26946.0;
    ['flags']= 68;
    
}
SHORT_TRADE_1_2 = {
    ['tradenum']= 1953472373147572640;
    ['firmid']= 'SPBFUT';
    ['side_qualifier']= 0;
    ['account']= 'SPBFUTJRk1N';
    ['lower_discount']= 0.0;
    -- station_id: ;
    ['client_qualifier']= 0;
    ['otc_post_trade_indicator']= 0;
    ['block_securities']= 0;
    -- order_exchange_code: ;
    -- clearing_firmid: ;
    ['kind']= 1;
    ['liquidity_indicator']= 0;
    ['accruedint']= 0.0;
    ['settle_currency']= 'SUR';
    ['settlecode']= 'T1';
    ['exchange_comission']= 5.34;
    ['uid']= 77133;
    -- userid: ;
    ['settle_date']= 20220125;
    ['brokerref']= 'short open';
    ['trade_num']= 1953472373147572640;
    ['order_qty']= 0.0;
    -- lseccode: ;
    ['ext_trade_flags']= 0;
    -- extref: ;
    ['price2']= 0.0;
    ['qty']= 3.0;
    ['yield']= 0.0;
    ['canceled_uid']= 0;
    -- cpfirmid: ;
    ['reporate']= 0.0;
    ['seccode']= 'SRH2';
    ['trans_id']= 1000325;
    ['accrued2']= 0.0;
    ['class_code']= 'SPBFUT';
    ['tech_center_comission']= 0.0;
    -- system_ref: ;
    ['on_behalf_of_uid']= 0;
    ['investment_decision_maker_qualifier']= 0;
    ['repo2value']= 0.0;
    -- bank_acc_id: ;
    ['order_revision_number']= 0;
    ['order_price']= 0.0;
    ['clearing_comission']= 0.0;
    ['executing_trader_qualifier']= 0;
    ['client_code']= 'SPBFUTJRk1N';
    -- clearing_bank_accid: ;
    -- exchange_code: ;
    ['cross_rate']= 0.0;
    ['capacity']= 0;
    ['mleg_base_sid']= -1;
    ['trade_currency']= 'SUR';
    ['waiver_flag']= 0;
    ['client_short_code']= 0;
    ['broker_comission']= 0.0;
    ['value']= 80838.0;
    -- exec_market: ;
    ['repovalue']= 0.0;
    ['executing_trader_short_code']= 0;
    ['ordernum']= 1953472373147616650;
    ['period']= 1;
    ['upper_discount']= 0.0;
    ['sec_code']= 'SRH2';
    ['linked_trade']= 0;
    ['start_discount']= 0.0;
    ['investment_decision_maker_short_code']= 0;
    ['repoterm']= 0;
    ['order_num']= 1953472373147616650;
    ['price']= 26946.0;
    ['flags']= 68;
    
}
SHORT_TRADE_1_3 = {
    ['tradenum']= 1953472373147572640;
    ['firmid']= 'SPBFUT';
    ['side_qualifier']= 0;
    ['account']= 'SPBFUTJRk1N';
    ['lower_discount']= 0.0;
    -- station_id: ;
    ['client_qualifier']= 0;
    ['otc_post_trade_indicator']= 0;
    ['block_securities']= 0;
    -- order_exchange_code: ;
    -- clearing_firmid: ;
    ['kind']= 1;
    ['liquidity_indicator']= 0;
    ['accruedint']= 0.0;
    ['settle_currency']= 'SUR';
    ['settlecode']= 'T1';
    ['exchange_comission']= 5.34;
    ['uid']= 77133;
    -- userid: ;
    ['settle_date']= 20220125;
    ['brokerref']= 'short open';
    ['trade_num']= 1953472373147572640;
    ['order_qty']= 0.0;
    -- lseccode: ;
    ['ext_trade_flags']= 0;
    -- extref: ;
    ['price2']= 0.0;
    ['qty']= 3.0;
    ['yield']= 0.0;
    ['canceled_uid']= 0;
    -- cpfirmid: ;
    ['reporate']= 0.0;
    ['seccode']= 'SRH2';
    ['trans_id']= 1000325;
    ['accrued2']= 0.0;
    ['class_code']= 'SPBFUT';
    ['tech_center_comission']= 0.0;
    -- system_ref: ;
    ['on_behalf_of_uid']= 0;
    ['investment_decision_maker_qualifier']= 0;
    ['repo2value']= 0.0;
    -- bank_acc_id: ;
    ['order_revision_number']= 0;
    ['order_price']= 0.0;
    ['clearing_comission']= 0.0;
    ['executing_trader_qualifier']= 0;
    ['client_code']= 'SPBFUTJRk1N';
    -- clearing_bank_accid: ;
    -- exchange_code: ;
    ['cross_rate']= 0.0;
    ['capacity']= 0;
    ['mleg_base_sid']= -1;
    ['trade_currency']= 'SUR';
    ['waiver_flag']= 0;
    ['client_short_code']= 0;
    ['broker_comission']= 0.0;
    ['value']= 80838.0;
    -- exec_market: ;
    ['repovalue']= 0.0;
    ['executing_trader_short_code']= 0;
    ['ordernum']= 1953472373147616650;
    ['period']= 1;
    ['upper_discount']= 0.0;
    ['sec_code']= 'SRH2';
    ['linked_trade']= 0;
    ['start_discount']= 0.0;
    ['investment_decision_maker_short_code']= 0;
    ['repoterm']= 0;
    ['order_num']= 1953472373147616650;
    ['price']= 26946.0;
    ['flags']= 68;
    
}


SHORT_TRADE_2_1 = {
    ['tradenum']= 1953472373147572641;
    ['firmid']= 'SPBFUT';
    ['side_qualifier']= 0;
    ['account']= 'SPBFUTJRk1N';
    ['lower_discount']= 0.0;
    -- station_id: ;
    ['client_qualifier']= 0;
    ['otc_post_trade_indicator']= 0;
    ['block_securities']= 0;
    -- order_exchange_code: ;
    -- clearing_firmid: ;
    ['kind']= 1;
    ['liquidity_indicator']= 0;
    ['accruedint']= 0.0;
    ['settle_currency']= 'SUR';
    ['settlecode']= 'T1';
    ['exchange_comission']= 1.78;
    ['uid']= 77133;
    -- userid: ;
    ['settle_date']= 20220125;
    ['brokerref']= 'short open';
    ['trade_num']= 1953472373147572641;
    ['order_qty']= 0.0;
    -- lseccode: ;
    ['ext_trade_flags']= 0;
    -- extref: ;
    ['price2']= 0.0;
    ['qty']= 1.0;
    ['yield']= 0.0;
    ['canceled_uid']= 0;
    -- cpfirmid: ;
    ['reporate']= 0.0;
    ['seccode']= 'SRH2';
    ['trans_id']= 1000325;
    ['accrued2']= 0.0;
    ['class_code']= 'SPBFUT';
    ['tech_center_comission']= 0.0;
    -- system_ref: ;
    ['on_behalf_of_uid']= 0;
    ['investment_decision_maker_qualifier']= 0;
    ['repo2value']= 0.0;
    -- bank_acc_id: ;
    ['order_revision_number']= 0;
    ['order_price']= 0.0;
    ['clearing_comission']= 0.0;
    ['executing_trader_qualifier']= 0;
    ['client_code']= 'SPBFUTJRk1N';
    -- clearing_bank_accid: ;
    -- exchange_code: ;
    ['cross_rate']= 0.0;
    ['capacity']= 0;
    ['mleg_base_sid']= -1;
    ['trade_currency']= 'SUR';
    ['waiver_flag']= 0;
    ['client_short_code']= 0;
    ['broker_comission']= 0.0;
    ['value']= 26945.0;
    -- exec_market: ;
    ['repovalue']= 0.0;
    ['executing_trader_short_code']= 0;
    ['ordernum']= 1953472373147616650;
    ['period']= 1;
    ['upper_discount']= 0.0;
    ['sec_code']= 'SRH2';
    ['linked_trade']= 0;
    ['start_discount']= 0.0;
    ['investment_decision_maker_short_code']= 0;
    ['repoterm']= 0;
    ['order_num']= 1953472373147616650;
    ['price']= 26945.0;
    ['flags']= 68;
}
SHORT_TRADE_2_2 = {
    ['tradenum']= 1953472373147572641;
    ['firmid']= 'SPBFUT';
    ['side_qualifier']= 0;
    ['account']= 'SPBFUTJRk1N';
    ['lower_discount']= 0.0;
    -- station_id: ;
    ['client_qualifier']= 0;
    ['otc_post_trade_indicator']= 0;
    ['block_securities']= 0;
    -- order_exchange_code: ;
    -- clearing_firmid: ;
    ['kind']= 1;
    ['liquidity_indicator']= 0;
    ['accruedint']= 0.0;
    ['settle_currency']= 'SUR';
    ['settlecode']= 'T1';
    ['exchange_comission']= 1.78;
    ['uid']= 77133;
    -- userid: ;
    ['settle_date']= 20220125;
    ['brokerref']= 'short open';
    ['trade_num']= 1953472373147572641;
    ['order_qty']= 0.0;
    -- lseccode: ;
    ['ext_trade_flags']= 0;
    -- extref: ;
    ['price2']= 0.0;
    ['qty']= 1.0;
    ['yield']= 0.0;
    ['canceled_uid']= 0;
    -- cpfirmid: ;
    ['reporate']= 0.0;
    ['seccode']= 'SRH2';
    ['trans_id']= 1000325;
    ['accrued2']= 0.0;
    ['class_code']= 'SPBFUT';
    ['tech_center_comission']= 0.0;
    -- system_ref: ;
    ['on_behalf_of_uid']= 0;
    ['investment_decision_maker_qualifier']= 0;
    ['repo2value']= 0.0;
    -- bank_acc_id: ;
    ['order_revision_number']= 0;
    ['order_price']= 0.0;
    ['clearing_comission']= 0.0;
    ['executing_trader_qualifier']= 0;
    ['client_code']= 'SPBFUTJRk1N';
    -- clearing_bank_accid: ;
    -- exchange_code: ;
    ['cross_rate']= 0.0;
    ['capacity']= 0;
    ['mleg_base_sid']= -1;
    ['trade_currency']= 'SUR';
    ['waiver_flag']= 0;
    ['client_short_code']= 0;
    ['broker_comission']= 0.0;
    ['value']= 26945.0;
    -- exec_market: ;
    ['repovalue']= 0.0;
    ['executing_trader_short_code']= 0;
    ['ordernum']= 1953472373147616650;
    ['period']= 1;
    ['upper_discount']= 0.0;
    ['sec_code']= 'SRH2';
    ['linked_trade']= 0;
    ['start_discount']= 0.0;
    ['investment_decision_maker_short_code']= 0;
    ['repoterm']= 0;
    ['order_num']= 1953472373147616650;
    ['price']= 26945.0;
    ['flags']= 68;
}
SHORT_TRADE_2_3 = {
    ['tradenum']= 1953472373147572641;
    ['firmid']= 'SPBFUT';
    ['side_qualifier']= 0;
    ['account']= 'SPBFUTJRk1N';
    ['lower_discount']= 0.0;
    -- station_id: ;
    ['client_qualifier']= 0;
    ['otc_post_trade_indicator']= 0;
    ['block_securities']= 0;
    -- order_exchange_code: ;
    -- clearing_firmid: ;
    ['kind']= 1;
    ['liquidity_indicator']= 0;
    ['accruedint']= 0.0;
    ['settle_currency']= 'SUR';
    ['settlecode']= 'T1';
    ['exchange_comission']= 1.78;
    ['uid']= 77133;
    -- userid: ;
    ['settle_date']= 20220125;
    ['brokerref']= 'short open';
    ['trade_num']= 1953472373147572641;
    ['order_qty']= 0.0;
    -- lseccode: ;
    ['ext_trade_flags']= 0;
    -- extref: ;
    ['price2']= 0.0;
    ['qty']= 1.0;
    ['yield']= 0.0;
    ['canceled_uid']= 0;
    -- cpfirmid: ;
    ['reporate']= 0.0;
    ['seccode']= 'SRH2';
    ['trans_id']= 1000325;
    ['accrued2']= 0.0;
    ['class_code']= 'SPBFUT';
    ['tech_center_comission']= 0.0;
    -- system_ref: ;
    ['on_behalf_of_uid']= 0;
    ['investment_decision_maker_qualifier']= 0;
    ['repo2value']= 0.0;
    -- bank_acc_id: ;
    ['order_revision_number']= 0;
    ['order_price']= 0.0;
    ['clearing_comission']= 0.0;
    ['executing_trader_qualifier']= 0;
    ['client_code']= 'SPBFUTJRk1N';
    -- clearing_bank_accid: ;
    -- exchange_code: ;
    ['cross_rate']= 0.0;
    ['capacity']= 0;
    ['mleg_base_sid']= -1;
    ['trade_currency']= 'SUR';
    ['waiver_flag']= 0;
    ['client_short_code']= 0;
    ['broker_comission']= 0.0;
    ['value']= 26945.0;
    -- exec_market: ;
    ['repovalue']= 0.0;
    ['executing_trader_short_code']= 0;
    ['ordernum']= 1953472373147616650;
    ['period']= 1;
    ['upper_discount']= 0.0;
    ['sec_code']= 'SRH2';
    ['linked_trade']= 0;
    ['start_discount']= 0.0;
    ['investment_decision_maker_short_code']= 0;
    ['repoterm']= 0;
    ['order_num']= 1953472373147616650;
    ['price']= 26945.0;
    ['flags']= 68;
}